"""Add is_searchable to disease table

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('diseases', sa.Column('is_searchable', sa.Boolean(), nullable=True))
        op.execute("UPDATE diseases SET is_searchable = TRUE WHERE is_searchable IS NULL")
    except Exception as e:
        print(f"Column might already exist: {e}")
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('diseases', 'is_searchable')
    except Exception as e:
        print(f"Column might not exist: {e}")
        pass
    # ### end Alembic commands ###
