"""Add is_searchable to disease table

Revision ID: add_is_searchable
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_searchable'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('is_searchable', sa.Boolean(), nullable=True))
    op.execute("UPDATE diseases SET is_searchable = TRUE WHERE is_searchable IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diseases', 'is_searchable')
    # ### end Alembic commands ###
